return {
  -- Better git diff viewer
  {
    "sindrets/diffview.nvim",
    cmd = { "DiffviewOpen", "DiffviewClose", "DiffviewToggleFiles", "DiffviewFocusFiles", "DiffviewFileHistory" },
    keys = {
      { "<leader>gd", "<cmd>DiffviewOpen<cr>", desc = "DiffView Open" },
      { "<leader>gh", "<cmd>DiffviewFileHistory %<cr>", desc = "DiffView File History" },
      { "<leader>gH", "<cmd>DiffviewFileHistory<cr>", desc = "DiffView Branch History" },
    },
    opts = {
      enhanced_diff_hl = true,
      view = {
        default = {
          layout = "diff2_horizontal",
          winbar_info = false,
        },
        merge_tool = {
          layout = "diff3_horizontal",
          disable_diagnostics = true,
          winbar_info = true,
        },
        file_history = {
          layout = "diff2_horizontal",
          winbar_info = false,
        },
      },
      file_panel = {
        listing_style = "tree",
        tree_options = {
          flatten_dirs = true,
          folder_statuses = "only_folded",
        },
        win_config = {
          position = "left",
          width = 35,
          win_opts = {},
        },
      },
      file_history_panel = {
        log_options = {
          git = {
            single_file = {
              diff_merges = "combined",
            },
            multi_file = {
              diff_merges = "first-parent",
            },
          },
        },
        win_config = {
          position = "bottom",
          height = 16,
          win_opts = {},
        },
      },
      commit_log_panel = {
        win_config = {
          win_opts = {},
        },
      },
      default_args = {
        DiffviewOpen = {},
        DiffviewFileHistory = {},
      },
      hooks = {},
      keymaps = {
        disable_defaults = false,
        view = {
          { "n", "<tab>", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle the file panel" } },
          { "n", "gf", "<cmd>DiffviewFocusFiles<cr>", { desc = "Bring focus to the file panel" } },
          { "n", "g<C-x>", "<cmd>DiffviewRefresh<cr>", { desc = "Update stats and entries in the file list" } },
          { "n", "<leader>e", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle the file panel" } },
          { "n", "<leader>co", "<Cmd>DiffviewConflictChooseOurs<CR>", { desc = "Choose the OURS version" } },
          { "n", "<leader>ct", "<Cmd>DiffviewConflictChooseTheirs<CR>", { desc = "Choose the THEIRS version" } },
          { "n", "<leader>cb", "<Cmd>DiffviewConflictChooseBoth<CR>", { desc = "Choose BOTH versions" } },
          { "n", "<leader>cB", "<Cmd>DiffviewConflictChooseBase<CR>", { desc = "Choose the BASE version" } },
          { "n", "<leader>cN", "<Cmd>DiffviewConflictChooseNone<CR>", { desc = "Delete the conflict region" } },
        },
        file_panel = {
          { "n", "j", "<cmd>lua require('diffview.actions').next_entry()<cr>", { desc = "Next entry" } },
          { "n", "<down>", "<cmd>lua require('diffview.actions').next_entry()<cr>", { desc = "Next entry" } },
          { "n", "k", "<cmd>lua require('diffview.actions').prev_entry()<cr>", { desc = "Previous entry" } },
          { "n", "<up>", "<cmd>lua require('diffview.actions').prev_entry()<cr>", { desc = "Previous entry" } },
          { "n", "<cr>", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Open the diff" } },
          { "n", "o", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Open the diff" } },
          { "n", "l", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Open the diff" } },
          { "n", "<2-LeftMouse>", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Open the diff" } },
          { "n", "-", "<cmd>lua require('diffview.actions').toggle_stage_entry()<cr>", { desc = "Stage / unstage" } },
          { "n", "S", "<cmd>lua require('diffview.actions').stage_all()<cr>", { desc = "Stage all entries" } },
          { "n", "U", "<cmd>lua require('diffview.actions').unstage_all()<cr>", { desc = "Unstage all entries" } },
          { "n", "X", "<cmd>lua require('diffview.actions').restore_entry()<cr>", { desc = "Restore entry" } },
          { "n", "L", "<cmd>lua require('diffview.actions').open_commit_log()<cr>", { desc = "Open commit log" } },
          { "n", "zo", "<cmd>lua require('diffview.actions').open_fold()<cr>", { desc = "Expand fold" } },
          { "n", "h", "<cmd>lua require('diffview.actions').close_fold()<cr>", { desc = "Collapse fold" } },
          { "n", "zc", "<cmd>lua require('diffview.actions').close_fold()<cr>", { desc = "Collapse fold" } },
          { "n", "za", "<cmd>lua require('diffview.actions').toggle_fold()<cr>", { desc = "Toggle fold" } },
          { "n", "zR", "<cmd>lua require('diffview.actions').open_all_folds()<cr>", { desc = "Expand all folds" } },
          { "n", "zM", "<cmd>lua require('diffview.actions').close_all_folds()<cr>", { desc = "Collapse all folds" } },
          { "n", "<c-b>", "<cmd>lua require('diffview.actions').scroll_view(-0.25)<cr>", { desc = "Scroll view up" } },
          { "n", "<c-f>", "<cmd>lua require('diffview.actions').scroll_view(0.25)<cr>", { desc = "Scroll view down" } },
          { "n", "<tab>", "<cmd>lua require('diffview.actions').select_next_entry()<cr>", { desc = "Next entry" } },
          { "n", "<s-tab>", "<cmd>lua require('diffview.actions').select_prev_entry()<cr>", { desc = "Previous entry" } },
          { "n", "gf", "<cmd>lua require('diffview.actions').goto_file_edit()<cr>", { desc = "Open file" } },
          { "n", "<C-w><C-f>", "<cmd>lua require('diffview.actions').goto_file_split()<cr>", { desc = "Open file in split" } },
          { "n", "<C-w>gf", "<cmd>lua require('diffview.actions').goto_file_tab()<cr>", { desc = "Open file in tab" } },
          { "n", "i", "<cmd>lua require('diffview.actions').listing_style()<cr>", { desc = "Toggle listing style" } },
          { "n", "f", "<cmd>lua require('diffview.actions').toggle_flatten_dirs()<cr>", { desc = "Flatten dirs" } },
          { "n", "R", "<cmd>lua require('diffview.actions').refresh_files()<cr>", { desc = "Refresh files" } },
          { "n", "<leader>e", "<cmd>lua require('diffview.actions').focus_files()<cr>", { desc = "Focus file panel" } },
          { "n", "<leader>b", "<cmd>lua require('diffview.actions').toggle_files()<cr>", { desc = "Toggle file panel" } },
          { "n", "g<C-x>", "<cmd>lua require('diffview.actions').cycle_layout()<cr>", { desc = "Cycle layout" } },
          { "n", "[x", "<cmd>lua require('diffview.actions').prev_conflict()<cr>", { desc = "Previous conflict" } },
          { "n", "]x", "<cmd>lua require('diffview.actions').next_conflict()<cr>", { desc = "Next conflict" } },
          { "n", "g?", "<cmd>lua require('diffview.actions').help('file_panel')<cr>", { desc = "Help" } },
          { "n", "<esc>", "<cmd>DiffviewClose<cr>", { desc = "Close diffview" } },
        },
        file_history_panel = {
          { "n", "g!", "<cmd>lua require('diffview.actions').options()<cr>", { desc = "Options" } },
          { "n", "<C-A-d>", "<cmd>lua require('diffview.actions').open_in_diffview()<cr>", { desc = "Open in diffview" } },
          { "n", "y", "<cmd>lua require('diffview.actions').copy_hash()<cr>", { desc = "Copy hash" } },
          { "n", "L", "<cmd>lua require('diffview.actions').open_commit_log()<cr>", { desc = "Commit log" } },
          { "n", "zR", "<cmd>lua require('diffview.actions').open_all_folds()<cr>", { desc = "Expand all" } },
          { "n", "zM", "<cmd>lua require('diffview.actions').close_all_folds()<cr>", { desc = "Collapse all" } },
          { "n", "j", "<cmd>lua require('diffview.actions').next_entry()<cr>", { desc = "Next" } },
          { "n", "<down>", "<cmd>lua require('diffview.actions').next_entry()<cr>", { desc = "Next" } },
          { "n", "k", "<cmd>lua require('diffview.actions').prev_entry()<cr>", { desc = "Previous" } },
          { "n", "<up>", "<cmd>lua require('diffview.actions').prev_entry()<cr>", { desc = "Previous" } },
          { "n", "<cr>", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Select" } },
          { "n", "o", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Select" } },
          { "n", "<2-LeftMouse>", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Select" } },
          { "n", "<c-b>", "<cmd>lua require('diffview.actions').scroll_view(-0.25)<cr>", { desc = "Scroll up" } },
          { "n", "<c-f>", "<cmd>lua require('diffview.actions').scroll_view(0.25)<cr>", { desc = "Scroll down" } },
          { "n", "<tab>", "<cmd>lua require('diffview.actions').select_next_entry()<cr>", { desc = "Next entry" } },
          { "n", "<s-tab>", "<cmd>lua require('diffview.actions').select_prev_entry()<cr>", { desc = "Previous entry" } },
          { "n", "gf", "<cmd>lua require('diffview.actions').goto_file_edit()<cr>", { desc = "Open file" } },
          { "n", "<C-w><C-f>", "<cmd>lua require('diffview.actions').goto_file_split()<cr>", { desc = "Open in split" } },
          { "n", "<C-w>gf", "<cmd>lua require('diffview.actions').goto_file_tab()<cr>", { desc = "Open in tab" } },
          { "n", "<leader>e", "<cmd>lua require('diffview.actions').focus_files()<cr>", { desc = "Focus files" } },
          { "n", "<leader>b", "<cmd>lua require('diffview.actions').toggle_files()<cr>", { desc = "Toggle files" } },
          { "n", "g<C-x>", "<cmd>lua require('diffview.actions').cycle_layout()<cr>", { desc = "Cycle layout" } },
          { "n", "g?", "<cmd>lua require('diffview.actions').help('file_history_panel')<cr>", { desc = "Help" } },
          { "n", "<esc>", "<cmd>DiffviewClose<cr>", { desc = "Close" } },
        },
        option_panel = {
          { "n", "<tab>", "<cmd>lua require('diffview.actions').select_entry()<cr>", { desc = "Select" } },
          { "n", "q", "<cmd>lua require('diffview.actions').close()<cr>", { desc = "Close" } },
          { "n", "g?", "<cmd>lua require('diffview.actions').help('option_panel')<cr>", { desc = "Help" } },
        },
      },
    },
  },

  -- Merge conflict markers
  {
    "akinsho/git-conflict.nvim",
    version = "*",
    event = "VeryLazy",
    opts = {
      default_mappings = {
        ours = "co",
        theirs = "ct",
        none = "c0",
        both = "cb",
        next = "]x",
        prev = "[x",
      },
      default_commands = true,
      disable_diagnostics = true,
      list_opener = "copen",
      highlights = {
        incoming = "DiffAdd",
        current = "DiffText",
      },
    },
  },
}
